apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-sheets-api
  labels:
    app: ai-sheets-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-sheets-api
  template:
    metadata:
      labels:
        app: ai-sheets-api
    spec:
      containers:
        - name: api
          image: ghcr.io/your-org/ai-sheets-saas:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: REDIS_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: JWT_SECRET
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-sheets-secrets
                  key: OPENAI_API_KEY
          readinessProbe:
            httpGet:
              path: /ops/readyz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /ops/livez
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-sheets-api
spec:
  selector:
    app: ai-sheets-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
